### PR TITLE
migrate to svelte 5 and update dependencies

### PR DESCRIPTION
**Pull request by grmbyrn**
* Migrate from Svelte 4 to Svelte 5 as mentioned in this [issue](https://github.com/torrust/torrust-website/issues/106).
* Update dependencies in `package.json` such as Vite which were preventing the successful migration to Svelte 5.
* Upgrade ESLint to v9 as v8 has recently reached end of life and is no longer maintained, as mentioned [here](https://eslint.org/docs/latest/use/migrate-to-9.0.0).
* Upgrade Sass as current syntax is deprecated as mentioned [here](https://sass-lang.com/documentation/breaking-changes/legacy-js-api/)
* Remove `/contributors` route as it is redundant since we now display GitHub contributors on home page and on Community page. Existing individual contributor pages have been retained and are accessible by clicking on the author's name in the blog post.
* Remove Histoire as it doesn't support Vite at the minute. There is currently a [PR](https://github.com/histoire-dev/histoire/pull/770) open to fix this, so Histoire can be added back later if needed.
* When navigating to a new page, the site wouldn't scroll up to the top as would be expected. As found [here](https://github.com/sveltejs/kit/pull/8723), this seems to be a Svelte issue. Solve this by adding the below code to the script block of routes/+layout.svelte and bind to page content:

```
import { onNavigate } from '$app/navigation';
let contentDiv: HTMLElement | null = null;

onNavigate((navigation) => {
    return new Promise((resolve) => {
	const transition = document.startViewTransition(async () => {
		if (contentDiv) {
			// Fix scroll
			contentDiv.scrollTop = 0;
		}
		resolve();
		await navigation.complete;
	});
    });
});

...

<div id="app-container">
    <Header />
    <div bind:this={contentDiv} class="content">
	{@render children?.()}
	<Footer />
    </div>
</div>
```

### CODE REVIEW

**Review by josecelano — APPROVED** [review]
Great job @grmbyrn!

**Comment by josecelano** [comment]
ACK 3f22176554731ad215c04d352c5fecae799f92a4

**Comment by da2ce7** [comment]
Really Good Work @grmbyrn  :)

**Comment by grmbyrn** [comment]
> Great job @grmbyrn!

Thanks, @josecelano and @da2ce7 I appreciate it!

**Pull request merged**
