### PR TITLE
remove vertical scroll bar

### PR DESCRIPTION
**Pull request by grmbyrn**
* Remove vertical scroll bar on all `routes/(pages)` as mentioned [here](https://github.com/torrust/torrust-website/pull/113#pullrequestreview-2433652719) using the following:

```
.content-preview {
	overflow-y: scroll;
	scrollbar-width: none;
	-ms-overflow-style: none;
	padding-top: 0rem;
}
```
* Edit lists on all `routes/(pages)` to ensure style consistency.

### CODE REVIEW

**Review by josecelano — CHANGES_REQUESTED** [review]
Hi @grmbyrn the vertical scroll bar was only hidden:

image

I think this is worse than the previous version because you don't even know what you are scrolling. You must know that moving the mouse wheel inside the article body scrolls the article content. I think that's not obvious. I think we should either:

1. Scroll with the window bar
2. Show the div vertical scroll bar

**Review by josecelano — CHANGES_REQUESTED** [review]
Hi @grmbyrn now the scroll works fine, but when you click on a TOC item the contents dones not scroll to that section:

image

**Comment by grmbyrn** [comment]
> Hi @grmbyrn now the scroll works fine, but when you click on a TOC item the contents dones not scroll to that section:

Hi @josecelano I reached out for help on Melt's Discord. The maintainer TGlide helped with this [PR](https://github.com/torrust/torrust-website/pull/118) which I used for my most recent commit.

I also spoke to Chris the core maintainer for Skeleton as I tried to implement their solution. He told me that they are in the process of phasing out their in-house Table of Contents in v3 and also recommend Melt UI to SvelteKit users [in their new docs](https://skeleton-next-4d21bca20-skeleton-labs.vercel.app/docs/resources/cookbook/table-of-contents).

**Comment by da2ce7** [comment]
Hello, @grmbyrn in the latest comment please put @TGlide as the author. (yourself as the committer)

**Comment by grmbyrn** [comment]
> Hello, @grmbyrn in the latest comment please put @TGlide as the author. (yourself as the committer)

Hi @da2ce7 I've changed the last commit to make @TGlide author and myself committer.

**Comment by da2ce7** [comment]
@grmbyrn unfortunately you didn't get his email correct, the author should be `tglide <26071571+TGlide@users.noreply.github.com>` taken from @TGlide comment.

**Comment by grmbyrn** [comment]
> @grmbyrn unfortunately you didn't get his email correct, the author should be `tglide <26071571+TGlide@users.noreply.github.com>` taken from @TGlide comment.

Hi @da2ce7 I've made that change so now `Author: TGlide <26071571+TGlide@users.noreply.github.com>` in git log.

**Comment by josecelano** [comment]
ACK 5078729deb6a1f69f70624dfd90f49582d8a039d

**Pull request merged**
