### PR TITLE
fix issues with v2

### LINKED ISSUE #6: Key features list width should be 100%
### Current

image

### Expected (Figma)

### LINKED ISSUE #12: Minor bugs in homepage
### Link to demo

Links to the demo don't work.

image

### Learn more

Links to specific Index and Tracker pages don't work

image

### Number of latest articles

Current:

image

Expected:

image

### LINKED ISSUE #25: Homapage cards don't have the same padding as design
Current:

image

Expected:

image

- [ ] Top and bottom padding is not the same
- [ ] The font size looks larger
- [ ] "Learn more" link is not aligned to the right

### LINKED ISSUE #28: Ask the designer how we should implement navigation between blog posts
Current:

image

Expected:

It was not included in the original design.

### LINKED ISSUE #30: Remove `#` prefix from titles
Current:

image

Expected:

There is no hashtag at the beginning of the title.

image

### LINKED ISSUE #36: Ask the designer how to implement highlighted terms or sentences in markdown
We use `backticks` to highlight some words or sentences in the blog posts.

For example (`list-only`):

```text
The API generates a magnet-link for the info-hash and adds that magnet-link to the client in `list-only` mode. The clients returns the torrent file.
```

Current:

image

Expected:

Not implemented in the original design.

### LINKED ISSUE #43: Font style in feature card is not the same as in the original design
Relates to: https://github.com/torrust/torrust-website-v2/issues/42

Current:

image

Expected:

image

- [ ] Box size is not the same
- [ ] Font size is not the same (maybe missing the "bold" attribute).

### PR DESCRIPTION
**Pull request by grmbyrn**
* moved posts for index and tracker into `TorrustIndexPost.svelte` and `TorrustTrackerPost.svelte`
* [Key features list width should be 100% #6](https://github.com/torrust/torrust-website-v2/issues/6)
* [Review design for table of contents #8](https://github.com/torrust/torrust-website-v2/issues/8)
* [Minor bugs in homepage #12](https://github.com/torrust/torrust-website-v2/issues/12)
* [Homepage cards don't have the same padding as design #25](https://github.com/torrust/torrust-website-v2/issues/25)
* [Top menu padding is not the same as the design #26](https://github.com/torrust/torrust-website-v2/issues/26)
* [Related Post section does not look like the standard blog post list #27](https://github.com/torrust/torrust-website-v2/issues/27)
* [Ask the designer how we should implement navigation between blog posts #28](https://github.com/torrust/torrust-website-v2/issues/28)
* [Ask the designer how to implement share links in blog posts #29](https://github.com/torrust/torrust-website-v2/issues/29)
* [Remove # prefix from titles #30](https://github.com/torrust/torrust-website-v2/issues/30)
* [Ask the designer how to implement highlighted terms or sentences in markdown #36](https://github.com/torrust/torrust-website-v2/issues/36)
* [Font style in feature card is not the same as in the original design #43](https://github.com/torrust/torrust-website-v2/issues/43)

### CODE REVIEW

**Comment by josecelano** [comment]
ACK 19437dd83738489a58ed7aff44560c954978ac69

**Review by josecelano — APPROVED** [review]
Good job @grmbyrn, just a couple of comments:

1. I'm closing only the issues I consider finished 100%. I  commented on the ones I think there are pending things to do.
2. Make sure the linter passes before opening the PR and fix it if it fails after opening the PR.
3. Make sure to follow the design as much as possible (pixel). I think it's **very important** to implement exactly what the designers gave us. They have their reasons and in my opinion the final site looks much worse with many mini changes.

**Comment by grmbyrn** [comment]
> Good job @grmbyrn, just a couple of comments:
> 
> 1. I'm closing only the issues I consider finished 100%. I  commented on the ones I think there are pending things to do.
> 2. Make sure the linter passes before opening the PR and fix it if it fails after opening the PR.
> 3. Make sure to follow the design as much as possible (pixel). I think it's **very important** to implement exactly what the designers gave us. They have their reasons and in my opinion the final site looks much worse with many mini changes.

That's no problem. For the linters, I ran them before and had no error. The error after opening the PR indicates an issue in `Hero.svelte` but nothing comes up when I check it.

**Comment by josecelano** [comment]
> > Good job @grmbyrn, just a couple of comments:
> > 
> > 1. I'm closing only the issues I consider finished 100%. I  commented on the ones I think there are pending things to do.
> > 2. Make sure the linter passes before opening the PR and fix it if it fails after opening the PR.
> > 3. Make sure to follow the design as much as possible (pixel). I think it's **very important** to implement exactly what the designers gave us. They have their reasons and in my opinion the final site looks much worse with many mini changes.
> 
> That's no problem. For the linters, I ran them before and had no error. The error after opening the PR indicates an issue in `Hero.svelte` but nothing comes up when I check it.

In those cases you can run `npm run format` and check is there was a git change (`git status`). I don't know why it's not showing the error.

I guess you mean this:

image

**Pull request merged**
