### PR TITLE
add article/ to url for each blog post

### PR DESCRIPTION
**Pull request by grmbyrn**
Change `(article)` to `article` so that it appears in the url for blog posts, for example `/article/released-v3-0-0-beta`, as in [Add a path segment in the URL for sections #73](https://github.com/torrust/torrust-website/issues/73)

### CODE REVIEW

**Review by josecelano — COMMENTED** [review]
Hi @grmbyrn any reason to use `article` instead of `blog`?

I think article is more generic, in the future we could have this prefix for new sections (tutorials, news, ...). All of them would be articles of a given section.

What do you think? I know we call them articles everywhere, and article sounds more professional and formal.

**Comment by grmbyrn** [comment]
> Hi @grmbyrn any reason to use `article` instead of `blog`?
> 
> I think article is more generic, in the future we could have this prefix for new sections (tutorials, news, ...). All of them would be articles of a given section.
> 
> What do you think? I know we call them articles everywhere, and article sounds more professional and formal.

Hi @josecelano I called it article because that's what it had been when it was in () as an anonymous route, and also because we currently have a blog route and you can't have two with the same name. The route for blog can be changed, eg: /blogs, and article/article-name could then be changed to blog/article-name.

**Comment by josecelano** [comment]
> > Hi @grmbyrn any reason to use `article` instead of `blog`?
> > I think article is more generic, in the future we could have this prefix for new sections (tutorials, news, ...). All of them would be articles of a given section.
> > What do you think? I know we call them articles everywhere, and article sounds more professional and formal.
> 
> Hi @josecelano I called it article because that's what it had been when it was in () as an anonymous route, and also because we currently have a blog route and you can't have two with the same name. The route for blog can be changed, eg: /blogs, and article/article-name could then be changed to blog/article-name.

I would do it like this:

https://torrust.com/blog
https://torrust.com/blog/released-v3-0-0

Which is, I think, very common. (I guess you can have an index page in the folder). If that's not possible in Svelte (I don't think so) we can use:

https://torrust.com/blog
https://torrust.com/blog-post/released-v3-0-0

**Comment by grmbyrn** [comment]
> > > Hi @grmbyrn any reason to use `article` instead of `blog`?
> > > I think article is more generic, in the future we could have this prefix for new sections (tutorials, news, ...). All of them would be articles of a given section.
> > > What do you think? I know we call them articles everywhere, and article sounds more professional and formal.
> > 
> > 
> > Hi @josecelano I called it article because that's what it had been when it was in () as an anonymous route, and also because we currently have a blog route and you can't have two with the same name. The route for blog can be changed, eg: /blogs, and article/article-name could then be changed to blog/article-name.
> 
> I would do it like this:
> 
> https://torrust.com/blog https://torrust.com/blog/released-v3-0-0
> 
> Which is, I think, very common. (I guess you can have an index page in the folder). If that's not possible in Svelte (I don't think so) we can use:
> 
> https://torrust.com/blog https://torrust.com/blog-post/released-v3-0-0

I think that the route for blog and the route for individual posts prevent that, but I can change article to blog-post so it appears as https://torrust.com/blog-post/released-v3-0-0, as you suggested.

**Comment by josecelano** [comment]
> https://torrust.com/blog
> https://torrust.com/blog/released-v3-0-0

HI @grmbyrn I found this example:

https://github.com/AdrienLF/svelte-blog

Which uses this format:

- https://www.icono-search.com/blog
- https://www.icono-search.com/blog/The%20Best%20Video%20Search%20Engine

**Pull request closed without merging**
